apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bs-python-app04
  description: Python app that displays time - named bs-python-app04
  tags:
    - python
    - flask
  annotations:
    github.com/project-slug: ricardoandre-97/bs-python-app04
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental